Added button in ETS View that sends user to Moodle website
ApplETS/Notre-Dame-v3 pull request #39
Opened 2019-02-02 17:53 UTC by filipearker

2019-02-03 18:41 UTC, Sonphil requested changes
Tu sembles avoir des problèmes de formatage. Tu devrais exécuter commande `./gradlew ktlintCheck` pour vérifier le formatage.

Pourrais-tu aligner le bouton à gauche et ajouter un espace avec ceux du dessus?

2019-03-12 19:29 UTC, Sonphil commented
:thinking:

2019-03-17 23:49 UTC, Sonphil requested changes

2019-03-17 23:49 UTC, Sonphil commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/presentation/ets/EtsFragment.kt
> +        etsViewModel.navigateToUri.observe(this, EventObserver {
Utilise le `etsViewModel.navigateToUri` qui est juste en haut.

2019-03-18 00:40 UTC, filipearker commented
![device-2019-03-17-204018](https://user-images.githubusercontent.com/25646135/54500629-edc76a80-48f4-11e9-9b25-aef8d06df0d6.png)

2019-03-18 01:18 UTC, Sonphil commented
J'ai corrigé le problème de positionnement et de marges.

2019-03-18 01:20 UTC, Sonphil commented
![image](https://user-images.githubusercontent.com/22182973/54501216-51a06200-48fa-11e9-88ed-b04d9c4bf130.png)
![image](https://user-images.githubusercontent.com/22182973/54501219-5a913380-48fa-11e9-9e6a-56212bcedb96.png)

2019-03-18 01:20 UTC, Sonphil approved these changes

2019-03-18 01:49 UTC, merged