Merge new-security-fragment into master
ApplETS/Notre-Dame-v3 pull request #40
Opened 2019-02-06 04:24 UTC by MachoBandido08

Étant donné que la fonctionnalité de télécharger la description des types d'urgence n'est pas si importante, je ne l'ai pas mis la fonctionnalité de télécharger la description du type d'urgence. Je le ferai plus tard.
![20190205_133034](https://user-images.githubusercontent.com/44484236/52320369-fabf7880-299c-11e9-8eff-daa24b746c42.gif)

2019-02-07 13:47 UTC, zaclimon requested changes
À l'exception des changements que j'ai remarqués (Incluant les marges pour le `RecyclerView` aussi) nice job! L'intégration de la carte est :fire:.

@Hamtara Is that how you were seeing it?

2019-02-07 13:47 UTC, zaclimon commented on android/app/src/main/res/layout/fragment_security.xml
> +                android:layout_width="45dp"
Dans les spécifications de Material Design, les [listes à 2 éléments](https://material.io/design/components/lists.html?image=https%3A%2F%2Fstorage.googleapis.com%2Fspec-host-backup%2Fmio-design%252Fassets%252F1-YqqvjVvKr2aWHg6yQ9KOP9yFbk-4o9t%252Flist-spec-doubleline-individual.png#specs) doivent avoir des icônes de 40 dp en hauteur et en largeur.

2019-02-07 13:47 UTC, zaclimon commented on android/app/src/main/res/layout/fragment_security_detail.xml
> +        android:textAppearance="?android:attr/textAppearanceLarge" />
Je ne crois pas que le texte a nécessairement besoin d'être gros. Le système peut normalement ajuster le texte en fonction des paramètres de l'utilisateur. Tu peux utiliser le composant [MaterialButton](https://material.io/develop/android/components/material-button/) pour avoir les bonnes dimensions.

2019-02-07 13:47 UTC, zaclimon commented on android/app/src/main/res/layout/fragment_security.xml
> +                android:padding="10dp"
Les subheaders sont supposés avoir 16 dp de marge/padding. De cette manière, ça sera aligné avec les listes. Tu peux voir les specs que j'avais laissé sur mon dernier commentaire.

2019-02-07 13:47 UTC, zaclimon commented on android/app/src/main/res/layout/fragment_security.xml
> +                android:padding="10dp"
Same as above.

2019-02-07 13:47 UTC, zaclimon commented on android/app/src/main/res/layout/fragment_security.xml
> +                android:id="@+id/textView3"
Je crois qu'il serait mieux de changer le id parce qu'il est un peu difficile de déterminer quelle est la section représenté par le `TextView`.

2019-02-07 13:47 UTC, zaclimon commented on android/app/src/main/res/layout/fragment_security.xml
> +                android:id="@+id/textView5"
Same as above

2019-02-07 13:47 UTC, zaclimon commented on android/app/src/main/res/layout/fragment_security.xml
> +                android:id="@+id/textView6"
Same as above.

2019-02-07 13:47 UTC, zaclimon commented on android/app/src/main/res/layout/fragment_security.xml
> +                android:id="@+id/textView4"
Same as above.

2019-02-07 14:45 UTC, Sonphil requested changes
J'ai remarqué que la barre demeurait cachée lorsqu'on se rendait à ce fragment. Tu dois utiliser la ligne suivante `appBarLayout.setExpanded(true, true)` pour afficher la barre correctement.
![image](https://user-images.githubusercontent.com/22182973/52418793-d5c22700-2abc-11e9-87d1-98fc750f3f79.png)

Aussi, la barre devrait avoir le même comportement au défilement que les autres pages. Je crois que tu dois simplement ajouter le comportement à ta vue défilante avec la ligne suivante : `app:layout_behavior="@string/appbar_scrolling_view_behavior"`

2019-02-07 15:02 UTC, Sonphil requested changes

2019-02-07 15:02 UTC, Sonphil commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/presentation/security/CustomMapView.kt
> +    )
En Kotlin, tu n'as besoin de définir plusieurs constructeurs pour les custom views notamment grâce aux [valeurs par défaut](https://try.kotlinlang.org/#/Kotlin%20Koans/Introduction/Default%20arguments/Task.kt).

Tout d'abord, enlève tes constructuers et l'IDE te signelera une erreur. Par la suite, utilise la combinaison de touch ALT + Entrée pour afficher le menu suivant.
![image](https://user-images.githubusercontent.com/22182973/52420066-508c4180-2abf-11e9-883c-65d7a01b3664.png)
Sélectionne l'option qui  te permet d'obtenir le résultat suivant : 
![image](https://user-images.githubusercontent.com/22182973/52419840-e83d6000-2abe-11e9-84f9-0d726ae43649.png)

2019-02-07 15:14 UTC, Sonphil commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/presentation/security/SecurityDetailFragment.kt
> +        (activity as? MainActivity)?.toolbar!!.title = args.securityName
Le title ne pourrait pas être changé en utilisant le xml du graph?

J'ai fait une recherche rapide et j'ai vu la solution suivante : https://stackoverflow.com/questions/50599238/dynamic-actionbar-title-from-a-fragment-using-androidx-navigation

2019-02-08 04:36 UTC, MachoBandido08 commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/presentation/security/SecurityDetailFragment.kt
> +        (activity as? MainActivity)?.toolbar!!.title = args.securityName
merci

2019-02-08 05:33 UTC, Sonphil commented on android/app/src/main/res/layout/fragment_security.xml
> +    </LinearLayout>
Ce `linearLayout` est-il nécessaire. Tu ne pourrais pas déplacer la `MapView` et le `RecyclerView` dans le `ConstraintLayout` et éviter un niveau d'imbrication?

2019-02-09 14:57 UTC, zaclimon submitted a review, later dismissed

2019-02-10 02:14 UTC, Sonphil commented on android/app/build.gradle
> +    implementation 'com.google.android.gms:play-services-maps:16.0.0'
Ce n'est pas un architecture component. Pourrais-tu déplacer cette ligne?

2019-02-10 13:27 UTC, zaclimon commented on android/app/build.gradle
> +    implementation 'com.google.android.gms:play-services-maps:16.0.0'
Aussi, ajouter une variable pour la version de la librairie serait nice.

2019-02-13 05:16 UTC, MachoBandido08 commented
@Sonphil Ai-je bien accomplis tes demandes?

2019-02-13 15:58 UTC, Sonphil approved these changes

2019-02-13 20:43 UTC, merged