Small fixes
ApplETS/Notre-Dame-v3 pull request #53
Opened 2019-03-12 09:37 UTC by Sonphil

- Remove switch case (`when`) used to select the security HTML file. An index is now used instead.
- Fix naming problems (i.e. `security_recycler_view was` used instead of `rvRecyclerView`)
- Add `selectableItemBackground` to clickable items in `SecurityFragment`
- Center phone icons vertically in `SecurityFragment`
- Specify that `55` is an extension number
- Add phone icon to "Appel d'urgence" button in `SecurityDetailFragment`
- Fix title not restored when the Activity was recreated
- Fix `BottomNavigationView`'s visibility not restored when the Activity was recreated (caused by #51). Now, before triggering the navigation, we check if the current destination is equals to the splash fragment or the login fragment.

2019-03-12 12:45 UTC, zaclimon reviewed
Nice job for cleaning all this up! 👍 J'ai remarqué que le comportement du "back" button ne ferme pas l'application quand on est dans le dashboard. Est-ce que c'est normal?

2019-03-12 19:26 UTC, Sonphil commented
@zaclimon Je viens d'ajouter un if pour fermer l'app lorsqu'on appuie sur le bouton de retour alors qu'on est sur le tableau de bord.

2019-03-12 19:37 UTC, zaclimon submitted a review, later dismissed
Looks good to me! 👌

2019-03-12 20:14 UTC, MachoBandido08 requested changes
Merci pour ta correction de la partie sécurité cependant, dans le SecurityFragment, le boutton "back" sur le toolbar ne fonctionne plus. On peut cependant revenir au fragment ETS avec le bottom navigation bar de l'android. Je vais voir c'est quoi qui cause ce problème pour ensuite le corriger.

EDIT: Je viens de remarquer que ce problème n'est pas présent dans la branch Master donc il doit être causé par l'un des commits du PR.

2019-03-12 23:06 UTC, Sonphil commented
@MachoBandido08 J'ai corrigé le problème.

2019-03-13 00:08 UTC, MachoBandido08 approved these changes

2019-03-13 02:39 UTC, merged