Schedule change week
ApplETS/Notre-Dame-v3 pull request #56
Opened 2019-03-15 04:24 UTC by mykaelll87

![capture](https://user-images.githubusercontent.com/31320170/54408450-6b526700-46b8-11e9-92f4-59078102300e.gif)

La fonctionnalité permettant de voir plus toutes les semaines à l'horaire, de toutes les sessions

2019-03-15 13:19 UTC, zaclimon requested changes
Ouhh les "aesthetics" sont présents nice one! :+1:

Cela dit, j'ai remarqué que ton "p.m" est pas bien aligné sur ton écran quand il y a 4 chiffres pour l'heure. Par exemple "12:00 pm". Sur mon émulateur, ça paraît bien par contre.

Sinon, la raison pour laquelle je refuse les changements, c'est parce que le `ViewPager` retourne les semaines depuis le début du bac. Ça peut devenir lourd sur un appareil et c'est pas tant nécessaire. Pour être franc, j'aimais bien l'allure l'affichage de l'horaire pour une semaine en général.

En soi les tabs du `ViewPager` pourraient aller de la semaine courante jusqu'à la dernière semaine de la session actuelle.

2019-03-15 13:41 UTC, zaclimon commented
Aussi j'ai remarqué que le rouge pour le background du titre des cartes peut devenir un peu trop "overwhelming". J'ai laissé des screenshots avec le fond en blanc mais avec la police en rouge et noir pour déterminer qu'est-ce qui serait mieux. @ApplETS/android-reviewers ça serait nice si vous pouviez aussi donner un peu d'input à ce niveau. 

Nitpick: Est-ce que c'est normal que la première lettre du jour soit en minuscule? Je crois que ça doit être à cause des caractéristiques de la langue française. (1er screenshot à l'appui)
Nitpick 2: Lorsqu'il y a plusieurs cours dans une journée, les heures sont pas bien alignées (Plus visible dans le 2ème screenshot)

![Screenshot_1552657027](https://user-images.githubusercontent.com/1891861/54435201-5ac8dd80-4706-11e9-8709-2d324c74d924.png)
![Screenshot_1552657175](https://user-images.githubusercontent.com/1891861/54435203-5bfa0a80-4706-11e9-9248-1b188ea749e6.png)

2019-03-15 13:44 UTC, zaclimon commented on android/app/src/main/res/layout/sub_item_schedule.xml
> +        android:layout_marginStart="8dp"
Ça peut être ici que tu as laissé un peu trop de marge pour la disparité entre les différentes heures.

2019-03-15 13:45 UTC, zaclimon commented on android/app/src/main/res/layout/fragment_schedule.xml
> +                <!--<androidx.viewpager.widget.PagerTabStrip-->
Si tu comptais pas utiliser ces éléments, il serait préférable de les effacer altogether.

2019-03-15 13:47 UTC, zaclimon commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/presentation/schedule/week/ScheduleWeekAdapter.kt
> +                    DateUtils.FORMAT_NO_YEAR)
Kotlin fournit une [fonction](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/capitalize.html) bien pratique `capitalize()` qui permet de mettre la première lettre d'une phrase en majuscule si le besoin est.

2019-03-15 20:16 UTC, Sonphil commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/domain/FetchSeancesUseCase.kt
> +                    mediatorLiveData.value = Resource.error(latestError!!, seances)
Tu pourrais utiliser la méthode [isNullOrBlank](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/is-null-or-blank.html) et éviter d'utiliser `!!` en utilisnat `?:` pour spécifier un autre message d'erreur si `lastestError `est null.

2019-03-15 20:39 UTC, Sonphil commented
Le texte de la date de la journée est gris et il est sur un fond rouge. Par conséquent, il est un peu difficile à lire. Je pense que pourrais faire comme @zaclimon et le mettre sur un fond blanc. 

De plus, tu indiquais aussi la journée courante en italique. Je pense qu'il y aurait un moyen de le faire. Par exemple, on pourrait mettre la journée courante en rouge et les autres en noir. 
Voici un exemple dans une app d'université : https://dribbble.com/shots/3254683-Univ-Student-App
![image](https://user-images.githubusercontent.com/22182973/54460677-9ed8d400-4740-11e9-858c-32364e9a4f78.png)

L'auteur a indiqué la journée courante en affichant le mois en jaune.
Un autre exemple serait les apps de calendrier comme [Google Agenda](https://www.google.com/calendar/about/). Il font souvent ressortir la journée courante en le coloriant.
![image](https://user-images.githubusercontent.com/22182973/54460646-82d53280-4740-11e9-9dc3-2481403374d9.png)

2019-03-15 20:59 UTC, Sonphil commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/domain/FetchSeancesUseCase.kt
> +class FetchSeancesUseCase @Inject constructor(
Est-ce que `FetchSeancesUseCase` va chercher les séances de toutes les sessions? Je pense que tu pourrais juste aller celles de la session actuelle et celles de la session précédente/suivante lorsque l'utilisateur se rendu au bout de la session actuelle..

Sinon, dans le projet, il y a `FetchSessionsUseCase` et `FetchSessionSeancesUseCase`. Le premier permet d'obtenir les séances et le deuxième permet d'obtenir les séances pour une session donnée. Tu pourras les utiliser et rendre `FetchSeancesUseCase` plus petite.

2019-03-15 21:25 UTC, Sonphil commented
J'ai remarqué que tu avais des commits de @kovy42 dans ta PR. Si tu veux éviter ça dans le futur, un moyen serait d'utiliser la fonctionnalité de rebase de sorte que ta branche parte du dernier commit de la branche master.

2019-03-17 14:55 UTC, mykaelll87 commented
@zaclimon pour le viewpager, j'utilises [FragmentStatePagerAdapter](https://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter), qui théoriquement, garde juste les fragments de la semaine courante, passée et suivante, ce qui fait que peu importe le nombre de semaines devrait pas trop influencer la RAM
Si on veux quand même loader juste les cours présents et futurs

2019-03-17 15:28 UTC, mykaelll87 commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/domain/FetchSeancesUseCase.kt
> +class FetchSeancesUseCase @Inject constructor(
Ouais il va chercher toutes les sessions.
Si on veux changer le comportement de l'horaire, on pourrais soit juste loader les cours présents et futurs, ou trouver une manière de faire un infinite scroll, que j'ai pas encore

2019-03-18 12:12 UTC, zaclimon commented
Bon ça brise moins les yeux maintenant! Perso j'aurais fait sans dividers vu que la tendance pour les cartes semble se diriger vers ça mais c'est quand même joli overall. (Ça ressemble plus à un calendrier en fait. :date:)

Aussi @mykaelll87 c'est good que `FragmentStagePagerAdapter` travaille pas trop la RAM d'un appareil. Par contre, c'est rough pour la transition entre les différentes section du `ViewPager`.

![viewpagerbug](https://user-images.githubusercontent.com/1891861/54529173-7675f300-4955-11e9-8fa5-6e064bc643a8.gif)

2019-03-20 01:01 UTC, zaclimon commented
Autre petit glitch que quelqu'un a reporté, il n'y a qu'un local qui est reporté lorsqu'il y en a 2 ou plusieurs pour un TP par exemple. Ci-joint se trouve une comparaison avec la V2.

![1Room](https://user-images.githubusercontent.com/1891861/54651641-264c7d00-4a8a-11e9-92cf-3bc0944a7e42.png)

2019-03-20 01:55 UTC, mykaelll87 commented
Hmm, c'est dur à dire où le 2e local disparaît sans avoir un exemple des données
Also, vous vouliez faire quoi avec le behaviour d'affichage des cours? Il faudrait qu'on se decide avant que je puisse le fix

2019-03-20 04:40 UTC, Sonphil commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/domain/FetchSeancesUseCase.kt
> +class FetchSeancesUseCase @Inject constructor(
Tu connaissais la date à laquelle l'utilisateur est rendue right? Pourrais-tu alors détecter lorsque l'utilisateur a bientôt fini de défiler la session courante et commencer à charger la prochaine session?

2019-03-20 12:32 UTC, mykaelll87 commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/domain/FetchSeancesUseCase.kt
> +class FetchSeancesUseCase @Inject constructor(
Il y a un interface à implemanter pour le pager qui permet de detecter le scroll.
Tho, je pense pas que ça existe pour les tabs(qui sont scrollable)

2019-03-20 18:06 UTC, zaclimon commented
Est-ce que tu tu reçois tous les locaux normalement? (Genre par exemple quand tu fais un `Log.x()`) Si c'est pas le cas, il faudra sûrement ajuster ça.

Pour le comportement de l'affichage,  pas changé de la suggestion que j'ai fait so idéalement qu'on puisse juste voir la semaine actuelle comme premier onglet puis que les autres semaines puissent être affichés par la suite. @Sonphil Est-ce qu'on a accès aux horaires des examens finaux avec Signets?

2019-03-21 00:07 UTC, Sonphil commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/domain/FetchSeancesUseCase.kt
> +class FetchSeancesUseCase @Inject constructor(
Il s'agit d'afficher les semaines dans des tabs. Lorsque l'utilisateur arrive sur une semaine, tu dois charger les séances de la session et afficher les séances de cette semaine.

Tu pourrais te référer à la librairie suivante : https://github.com/Mulham-Raee/Horizontal-Calendar
Tu peux voir comment elle charge les jours dans les onglets, gère les scrolls, etc.

Si c'est quand même trop compliqué, tu pourrais peut-être utiliser une librairie comme celle-là et présenter un horaire par journée?

2019-03-21 00:09 UTC, Sonphil commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/domain/FetchSeancesUseCase.kt
> +class FetchSeancesUseCase @Inject constructor(
Une horaire par journée serait l'idéal parce que la vue par semaine pourrait devenir très chargée avec les séances, examens finaux, événements, etc

2019-03-21 00:10 UTC, Sonphil commented
Oui, on a accès aux examens finaux avec Signets.

2019-03-22 00:11 UTC, mykaelll87 commented
Et voilà, on montre maintenant juste la semaine présente et les futures

2019-03-22 00:15 UTC, mykaelll87 commented
Pour le truc des locals, selon le modèle on reçoit juste une string avec le local. Vu que j'ai toujours pas eu de cours avec 2 locaux, je peux pas guess comment ils sont envoyés/reçu/traité pour qu'il y ait une des 2 instances du cours qui disparaisse
Anyway, c'est peut-être juste mon avis, mais je pense que ce bug est en dehors du scope de la PR, so je pense qu'on devrait le faire séparément

2019-03-22 01:04 UTC, Sonphil commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/presentation/schedule/week/ScheduleWeekFragment.kt
> +            adapter.items = seances.groupBy {
Pourrais-tu déplacer le `groupBy` vers le ViewModel? Je pense que le fragment ne devrait pas avoir à le faire lui-même.

2019-03-22 01:13 UTC, zaclimon commented
@mykaelll87 D'accord, je vois. So en somme il faudrait qu'on ait un cas où il y a deux locaux pour qu'on puisse confirmer ce qui se passe. Si on se fie à la V2, on dirait que le cours à comme 2 séances mais bon. 

Je suis d'accord avec toi que cette situation devrait avoir son propre PR. :ok_hand: Une fois que le commentaire de @Sonphil sera réglé, ça pourra être merged!

2019-03-22 01:26 UTC, mykaelll87 commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/presentation/schedule/week/ScheduleWeekFragment.kt
> +            adapter.items = seances.groupBy {
En effet, jme souvenais plus de l'avoir mis là

2019-03-22 01:39 UTC, Sonphil commented
@mykaelll87 Si tu veux corriger le problème le que @zaclimon a mentionné à propos des séances avec plusieurs locaux, tu pourrais regarder la classe `SeanceEntity`.
```kotlin
@Entity
data class SeanceEntity(
    @PrimaryKey
    var dateDebut: Long,
    var dateFin: Long,
    var nomActivite: String,
    var local: String,
    var descriptionActivite: String,
    var libelleCours: String,
    var sigleCours: String,
    var groupe: String,
    var session: String
)
```
Comme tu peux voir, la clé primaire a été défini sur dateDebut. Afin de corriger le problème, je pense qu'il suffirait d'utiliser une clé composite avec les attributs `dateDebut` et `local`.

2019-03-22 01:40 UTC, mykaelll87 commented on android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/presentation/schedule/week/ScheduleWeekFragment.kt
> +            adapter.items = seances.groupBy {
Bin en fait, ce fragment a pas vraiment de stateful logic, donc il a pas de viewmodel. 
Je l'ai déplacé vers l'adapteur tho.

2019-03-24 12:19 UTC, zaclimon commented
@mykaelll87 C'est un bon step qu'on ne voit plus les semaines depuis le début du bac, mais looks like qu'on voit encore toutes les semaines depuis le début de la session. :open_mouth:

2019-03-24 16:57 UTC, mykaelll87 commented
Huh, j'étais certain d'avoir mis un filter sur les cours entrant pour ça

2019-03-24 17:11 UTC, mykaelll87 commented
Ah c'était parce que le type des dates des séances et celui des sessions n'était pas pareil, so je comparais des ms avec des s, c'est fix

2019-03-24 20:13 UTC, Sonphil commented
@mykaelll87 @zaclimon Dans la PR #75, J'ai corrigé le problème de la séance manquante lorsqu'il y a deux locales.

2019-03-24 21:53 UTC, zaclimon approved these changes

2019-03-24 21:54 UTC, zaclimon commented
Alright tout semble parfait dans ce cas! Je vais merge ce PR vu que ça fait un bout que c'est dispo pis je regarderai #75 par la suite @Sonphil. :ok_hand:

2019-03-25 00:32 UTC, merged

2019-03-25 00:33 UTC, zaclimon commented
Bon le tout a été merged, nice one @mykaelll87! :tada: